spring.application.name=service-platform

spring.datasource.url=jdbc:postgresql://ep-old-shape-b4csp1s4-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dt0Pu1sZNbDK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
